<?xml version="1.0" encoding="utf-8"?>
<TestRun id="f7101a10-5b45-4c44-9dfc-7792dad39322" name="TFSBUILD73$@TFSBUILD73 2019-11-01 06:24:09" runUser="NT AUTHORITY\NETWORK SERVICE" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2019-11-01T06:24:09.7096613-07:00" queuing="2019-11-01T06:24:09.7096613-07:00" start="2019-11-01T06:24:07.8746483-07:00" finish="2019-11-01T06:24:09.7126613-07:00" />
  <TestSettings name="default" id="9756e413-0da3-4d2a-b948-7290f7655bd9">
    <Deployment runDeploymentRoot="TFSBUILD73$_TFSBUILD73_2019-11-01_06_24_09" />
  </TestSettings>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="0" executed="0" passed="0" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="TFSBUILD73" outcome="Error" timestamp="2019-11-01T06:24:09.6606619-07:00">
        <Text>The active test run was aborted. Reason: Process is terminated due to StackOverflowException.&#xD;
</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>